### ISSUE TITLE
CLI interface improvements

### ISSUE THREAD

**Issue by clamdad** [tellor-io/telliot-feed-examples#103]
The CLI might be more clear if it included a flag to choose the reporting network (i.e. tellorx or tellorflex) and maybe the subnetwork (mainnet or testnet).  

Here are three possibilities:
- Single args: 
  - --network:  'x-eth', 'x-rinkeby',  'flex-polygon', or flex-mumbai' 
- Dual args: 
  - --network: 'x' or 'flex'.   
  - --testnet bool flag defaults to false.
- Just make the chain ID a required input

With such a flag, the users account would be chosen automatically.

If the user wanted to use a *specific* account, they could pass in the --account flag.  This would only make sense for flex.  It doesn't make sense for tellorx because the user would want telliot to rotate through the available accounts.

The current method of choosing the chain_id from the account can create confusion because accounts can be associated with more than one chain id.

**Comment by oraclown** [comment]
Good points.

I'm leaning towards just making the account flag optional, and also adding an optional chain ID flag.

- If neither are included, it grabs the first account from `.chained-accounts` with a corresponding chain ID listed in `~/telliot/main.yaml`. That account would have said chain ID at index 0 in its list.
- If only the account flag is included, it grabs the first account with a matching name and uses the chain ID of that account at index 0 of its chains list.
- If only the chain ID flag is included, it grabs the first account with a matching chain ID at index 0 of its chains list.
- If both account and chain ID flags are included, then it grabs the account with matching name and uses the chain ID specified by the flag. Throws an error if that `ChainedAccount` doesn't have said chain ID in its chains list.

I like and am open to the idea of rotating reporters, but doing so isn't supported currently. Also, I'm not sure if users even want that. I don't see myself rotating reporters, as I'm usually intentional about which account I'm using. Some are used for Flashbots, some have listed chain IDs, but I don't want to report with them because I don't want them to go into reporter lock.

Thoughts?

**Comment by clamdad** [comment]
Sound pretty much option 3, with one small difference.
The Chain-id (operating network) is the main user choice.  It defaults to the one from the config file, or can be overridden from the command line.  The only difference is that if the `-a` option is used, I'd suggest always throwing an error if the account is not associated with the chain_id chosen by the user.
