### ISSUE TITLE
Avoid submission retry when first submission fails because reward was already claimed

### ISSUE THREAD

**Issue by clamdad** [tellor-io/telliot-feed-examples#59]
See [this issue](https://github.com/tellor-io/telliot-core/issues/163)  for details

**Comment by clamdad** [comment]
Interim fix might be to submit without retries.

**Comment by tallywiesenberg** [comment]
I agree. I'm trying to think of the best way to do this, because we also don't want users to be unable to send transactions (the original purpose of retries)

solution suggestions (in order of size of build):
* if the submitValue tx has a contract reversion, sleep until time-based reward returns (interim small build)
* if the submitValue tx has a contract reversion, loop through the legacyIds by incrementing by 1, submit when a profitable one is found (medium)
* if the submitValue tx has a contract reversion, begin listening for tips and switch queryId when a profitable query is found (large)

please lmk if you have other suggestions, comments

**Comment by oraclown** [comment]
@clamdad @tallywiesenberg Can I close this? Reasoning:

Overall, I think retry functionality should just be reserved for other kinds of contract calls than `submitValue()`. Currently, if you fail to submit it won't retry. The reporter will just log the failure and go through the whole process of checking profitability once more, thereupon it'll discover that it's no longer cash money to report. Also, wasn't the syncing-of-reporters supposed to address this as well?

**Comment by clamdad** [comment]
Ok to close if we are no longer using wrote with retries.
